apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-persistance-volume
  namespace: oracle-namespace
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

