apiVersion: v1
kind: Namespace
metadata:
  name: oracle-namespace

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-persistance-volume
  namespace: oracle-namespace
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"